### ISSUE TITLE
not rendering in PDF export

### ISSUE THREAD

**Issue by marvin-te** [ckRobinson/multi-column-markdown#10]
Hello.
I really like your plugin and would love to use it for creating documents in markdown/Obsidian.
Sadly I just noticed, that the plugin doesn't currently work when exporting to PDF.
Is this feature planned for the future? When could it be potentually used?

**Comment by ckRobinson** [comment]
Hey thanks, I actually had not considered the export to PDF feature at all. Ideally everything should render properly when exporting so I'll definitely have to take a look and see if I can fix the problem.  Not sure how complex a problem it is going to be though, so I can't really put a timeline on it at this point.

**Comment by marvin-te** [comment]
Hey @ckRobinson do yo u have a plans on this, yet?
We would like to use this plugin for the meeting minutes in our student organization. These have to be published to all students at our university in PDF format. That‘s why this feature would be very important for us.

Thank you very much
Marvin

**Comment by ckRobinson** [comment]
Hey there, just released 0.5.0 which now includes this fix. I'll leave this issue open for now in case something pops up but from my tests everything seems to work fine. Feel free to let me know if you spot anything.

**Comment by mrickey** [comment]
Hi, This might be broken again. I am running 0.7.3, when I export a page to PDF, I get flat columns.

Or, might I be doing something wrong?
<img width="524" alt="2022-10-14 Multi-Column" src="https://user-images.githubusercontent.com/7904533/195929526-7e72e02b-42c1-4c67-8d62-22866e5e1855.png">

Thanks in advance,
Michael
