### ISSUE TITLE
Not working with checklists in preview mode.

### ISSUE THREAD

**Issue by valevasqc** [ckRobinson/multi-column-markdown#11]
Hi, I love your plugin, I had been trying to use columns for a long time and this works exactly as I wanted.
I have one issue though. I can't tick off checklists that are inside the columns in preview mode, I have to switch to editor and do it manually for it to be shown as crossed off.

**Comment by ckRobinson** [comment]
Hey there, I'll look into this and see what I can do to fix it asap.

**Comment by ckRobinson** [comment]
This should be now fixed as of 0.5.0. It has been tested for compatibility with native Obsidian checklists as the Tasks plugin and everything seems to work fine. If there is some other compatibility issue feel free to let me know.
