### ISSUE TITLE
Pure readme code doesn't work

### ISSUE THREAD

**Issue by mmfs37** [ckRobinson/multi-column-markdown#13]
![image](https://user-images.githubusercontent.com/100991030/161614119-9bb7edd4-fd6f-4cf0-af3c-2ceb474b1a41.png)
that image is that code copied from the readme

=== start-multi-column: <RandomRegionID>  
```settings  
number of columns: 3  
largest column: center  
```

#### Column 1

=== end-column ===

# Column 2

=== end-column ===

#### Column 3

=== end-multi-column

I cant figure out how to do 3 columns and that doesn't work either. Idk what to do.

**Comment by ckRobinson** [comment]
Does the start-multi-column tag in your document still contain "<RandomRegionID>"? That text in the README was supposed to be a placeholder so if that is still there try replacing it with any other text to see if that fixes the issue. I will update the README to make the examples directly copy/paste-able though.

**Comment by mmfs37** [comment]
just recorded how it doesnt work and some other glitches but now pure pasting even works. Idk 
Problem is prob my vault cause I have over 60 plugin and many many snippets.
