### ISSUE TITLE
Doesn't show iframes correctly

### ISSUE THREAD

**Issue by valevasqc** [ckRobinson/multi-column-markdown#14]
I tried adding iframes to the columns, but they keep glitching in and out (see the video).
I also can't add more than one iframe, it will only show one per row (see the first screenshot, there's supposed to be two iframes in the first row, but only one shows). It also won't show other text in the same row.
On the second screenshot, you can see that the iframes will also move around randomly, not in the column they're supposed to be.

https://user-images.githubusercontent.com/92452690/163443889-e9800a33-9643-45a7-91e3-6fabdc90e7de.mov
<img width="1280" alt="Screen Shot 2022-04-14 at 11 42 00 AM" src="https://user-images.githubusercontent.com/92452690/163444134-c10dab06-4da7-4538-b9be-d21cc3e5091c.png">
<img width="1280" alt="Screen Shot 2022-04-14 at 11 42 50 AM" src="https://user-images.githubusercontent.com/92452690/163444264-e8249644-4fce-4d3b-bcfc-c905c0d508c5.png">

**Comment by ckRobinson** [comment]
This was also fixed as of 0.5.0 so you should be good to go!
