### ISSUE TITLE
The === at the start and end of commands not working properly (maybe it's an error on my side)

### ISSUE THREAD

**Issue by Daselsdis** [ckRobinson/multi-column-markdown#16]
![imagen](https://user-images.githubusercontent.com/69808506/165590268-eae9fca3-8d87-4322-b830-1a35378f3490.png)
Please ignore my spanish text in the rest of the screen, I may be doing something wrong here, but as far as i can tell, obsidian just assumes that === is a highlight styling.

**Comment by Daselsdis** [comment]
Also, please forgive my manners, this seems like a great idea and the images I've seen of it are astounding and I'd love to see this become a more "mainstream feature in the future, it is great for styling and marking different thought processes and routes for some of the explanations I have to write.

**Comment by Daselsdis** [comment]
After some trial and error I've digured out that updating each and every === and using some place holders as "# a" in each space helped refresh it and it eventually kind of got working. Maybe it's not as urgent, but it is still a bit distracting, either way, I hope this gets fixed if it is even regarded as a serious problem and I hopie to see more people use this, when it finally updated the other side, the results look amazing and are just what I wanted

**Comment by ckRobinson** [comment]
Hey glad you eventually got it figured out. From the looks of it in the image I think you were missing a new line after the column settings which messed up the parsing somehow. Obsidian sends the text to the plugin in (basically) paragraphs so sometimes things can get a bit wonky when accidentally missing a new line. Its one of those on-going issues and I'm slowly trying improve the parsing logic so it doesn't happen as frequently.

As far as the highlighting of the column end tag goes, I initially set the syntax to the "===" not realized that "==" is markdown syntax for highlight. So yea when things don't render properly it looks strange but its a minor issue in my opinion. I have plans for adding in user defined column start, break, and end syntax so when that is added it wont be as much of an eye sore.
