### ISSUE TITLE
Multi-Column Does Not Render Until Note is Closed and Reopened

### ISSUE THREAD

**Issue by kscmint** [ckRobinson/multi-column-markdown#17]
I am working with Obsidian 14.7 and recently installed Multi-Column-Markdown. I really like it but if I create a new multi-column section or change an existing one, the changes do not render until I close the note and re-open it.

I currently have the following additional plugins installed:
- Advanced Tables
- Chesser
- Dataview
- DEVONlink
- File Tree Alternative
- Note Refactor
- Outliner
- Sliding Panes
- System Dark Mode
- Tag Wrangler

**Comment by ckRobinson** [comment]
Hi there, I don't have Obsidian Catalyst and therefore can't test on the Insider builds. If something has broken on 14.7 it may be a bug on Obsidian's side, or a change in the API, that is causing the issue. Sorry for the inconvenience, but if it is still broken when 14.7 is publicly released I will attempt to fix it ASAP.

**Comment by micwaab** [comment]
Hello,
Love your plugin—your webpage is also quite fetching.

Anyhow, I'm having the same issue as above.

Cheers.

**Comment by ckRobinson** [comment]
This does not appear to be happening on my end as of the public release of v0.14.15. If it is still an issue feel free to re-open the issue.
