### ISSUE TITLE
[Feature Request] Single Column setting

### ISSUE THREAD

**Issue by efemkay** [ckRobinson/multi-column-markdown#18]
I really like your approach to have the multi column plugin based on markdown syntax rather than code blocks. It allow users to fully utilise obsidian core features like backlinks.

Anyway, I see a potential use of this plugin as a container (especially if your roadmap to have it rendered for live preview). I would like to request for 1 column setting of your plugin. This would allow some creative layout by having, for example, 6 small paragraph inside the 1 column setting to have a card like layout.

hope you can consider that. tqs

**Comment by ckRobinson** [comment]
Hey, glad you like it. I could definitely add a single column option. Initially I didn't see the use case for just one column but I can see how that may be helpful to some people now that you mention it.

**Comment by ckRobinson** [comment]
Sorry this took so long, but single columns are now live in 0.6.0.
