### ISSUE TITLE
Multi-columns not displaying in Live Preview

### ISSUE THREAD

**Issue by RavHilton** [ckRobinson/multi-column-markdown#19]
In legacy mode, Multi-Columns isn't going to display in the Editor view and works as expected in the Preview view.  when using Live Preview, however, the old behaviour still persists and you only see the markdown, not the multi-columns when in Live Preview...

**Comment by RavHilton** [comment]
I've had a quick play with https://github.com/tnichols217/obsidian-columns which works in Live Preview, and I think the reason that works is because it lives within a backpack-enabled code block, whereas this plugin resides between "===" markers...

**Comment by ckRobinson** [comment]
Hi there, yea, as I list in the readme live preview is currently not supported. It is one of those things I would like to add but from my look into it will take a bit of time to work out and I'm still not entirely sure is possible yet. You are correct that obsidian-columns uses the ```codeblock syntax which obsidian automatically renders when using live preview (as far as I'm aware.) But I intentionally chose not to use that syntax when I wrote multi-column. When writing text in a codeblock obsidian handles the text differently so you lose access to some features, as well as breaking compatibility with other plugins, so I tried to keep as much cross compatibility as possible by writing my own syntax and parsing engine. Adding live preview support is on my TODO list though.

**Comment by nazgul** [comment]
Just putting in my vote for Live Preview. I love this plugin. I have some scripts which automatically add meetings from my calendar, and it includes an attendee list, which really gets out of control for large meetings. This plugin lets me tame that…until I start editing.

**Comment by nousernameavailableanymore** [comment]
I would also like to see this work in Live Preview.
In my personal workflow, the "reading mode" has no use at all anymore since Live Preview is available.

**Comment by quartzar** [comment]
+1 for support for Live Preview. This plugin is redundant without supporting this feature for me.

**Comment by Kongolan** [comment]
> Hi there, yea, as I list in the readme live preview is currently not supported. It is one of those things I would like to add but from my look into it will take a bit of time to work out and I'm still not entirely sure is possible yet. You are correct that obsidian-columns uses the ```codeblock syntax which obsidian automatically renders when using live preview (as far as I'm aware.) But I intentionally chose not to use that syntax when I wrote multi-column. When writing text in a codeblock obsidian handles the text differently so you lose access to some features, as well as breaking compatibility with other plugins, so I tried to keep as much cross compatibility as possible by writing my own syntax and parsing engine. Adding live preview support is on my TODO list though.

Thanks for all the insides. It's great that you keep in mind that typing the text in the columns is very important. For example, I would love to use the Cornell Method in Obsidian, but I can't. So don't limit it for creating dashboards, it should be a full fledged multi-column writing tool! Thus your idea to not use Codeblocks, is promising.

However it would still require to render our columns in live-preview mode, which currentlly drives me away from using your plugin. A compromise would be to have a setting in the option block of each column set, if it should render right away in live-preview with codeblocks maybe or only in reading mode. This would be very flexible. 

One problem about live-preview mode is still that editing this codeblocks breaks their appeareance, while I just want to have multiple panes for writing and not fiddling with the syntax (codeblocks) of a plugin.

**Comment by ckRobinson** [comment]
Hi all, Live Preview support has now been added as of 0.7.0 and works like any other ```codeblock in Obsidian. All core markdown syntax should be fully supported and render properly in the columns. However there will be some plugin cross-compatibility issues in live preview that are still only solved in reading mode due to when the data is being communicated by the other plugins. If you encounter any other issues with live preview feel free to open a new issue. My time to work on side projects has become more limited recently but will try to get fixes out as soon as I can.

**Comment by Kongolan** [comment]
Just tested the new live preview feature. And it works great!! Thanks a lot! 😍 However you should tidy up your documentation a bit and move all the old syntax in an own section. It's a bit confusing.
