### ISSUE TITLE
Issue with Content of table inside a column

### ISSUE THREAD

**Issue by TayThorian** [ckRobinson/multi-column-markdown#20]
Hi

I can use tables inside the columns and they work fine, but if I try inserting [[Ch 3.8 - Ranger|Ranger]] for example it shows [[Ch 3.8 - Ranger as the outcome

If I just use [[Ch 3.8 - Ranger]] the link works / shows correctly.

The # command to show a link to a heading works fine.

Any help would be appreciated.

**Comment by ckRobinson** [comment]
Hi there, sorry for the super late response. However, I don't think I understand the issue you are seeing. If this is still an on going problem for you could you provide some screenshots of exactly what is going on so I can better visualize the issue?

**Comment by ckRobinson** [comment]
Considering this issue solved and closing.
