### ISSUE TITLE
iframes flicker in and out

### ISSUE THREAD

**Issue by J-F2** [ckRobinson/multi-column-markdown#21]
![image](https://user-images.githubusercontent.com/96497580/170842527-9890e6e3-0bd5-444b-9237-820e7ae9792c.png)
![image](https://user-images.githubusercontent.com/96497580/170842540-9a38c20a-fa09-4cbf-b477-5cd994562d25.png)

an iframe inside of a column keeps flickering in and out. I saw an issue that said this was fixed in 0.50, but i am still having this problem in this version.

**Comment by ckRobinson** [comment]
Hi there, sorry it took so long but as of the latest release (0.6.0) this should be now fixed again. If it is still occurring feel free to let me know.
