### ISSUE TITLE
Issue with Dataview

### ISSUE THREAD

**Issue by YugiAsh01** [ckRobinson/multi-column-markdown#22]
Hello!

I've been using the plugin for some time now and it's been wonderful for my work; however, lately when I've been trying to use dataview tables within the columns, sometimes the table is displayed and sometimes it seems to glitch between the table being displayed and not displayed. This was not an issue before the latest version of Obsidian, so I'm not sure what could be the issue.

**Comment by ckRobinson** [comment]
Hey! Yea, it looks like there this must have slipped by in my testing. Funnily enough I actually had left a note to myself predicting that this issue might pop up but missed that as well. Anyways this should now be fixed in 0.6.1. Feel free to let me know if you notice any other issues!

**Comment by YugiAsh01** [comment]
Thanks for responding back so quickly! Everything seems to be working well now, though I have noticed that sometimes the columns either dont display at all, or glitch to display settings within the column itself which is odd, though it seems to fix itself once I reload the note so it is not really an pressing issue.

**Comment by ooker777** [comment]
This still happens in v0.6.3

**Comment by ckRobinson** [comment]
Sad to hear, will reopen and look back into this issue.

**Comment by ckRobinson** [comment]
Sorry it took so long, but this should now be fixed in 0.7.3. Will close issue, if problem persists let me know and will re-open.
