### ISSUE TITLE
Multi Column not showing todos at all

### ISSUE THREAD

**Issue by lennonruthven** [ckRobinson/multi-column-markdown#23]
[Editor View]
https://gyazo.com/c6c5f83e8bba38033fa5cb64bc33ca94

[Reading View]
https://gyazo.com/70719dc8d408f9ce242ef241f5138229

Never had this issue up until Today. I see that there was a recent update but I'm not GitHub or code literate. All my previous daily notes have had their todo's disappeared in Reading Mode magically. How inconvenient! 😝

**Comment by ckRobinson** [comment]
Hi there, sorry for the inconvenience, but this should now be fixed as of the new build, 0.6.2.

**Comment by lennonruthven** [comment]
Perfect. Thanks so much.
