### ISSUE TITLE
Updating from within Obsidian doesn't work

### ISSUE THREAD

**Issue by metawops** [ckRobinson/multi-column-markdown#24]
Hi Cameron,

I just installed your plugin from within Obsidian and got version 0.6.0 installed.
Obsidian tells me that there's a newer version (0.6.2) and offers an update button.
However, after clicking on it the plugin version stays at 0.6.0.
Could you check on that?
I'm having an issue with a Dataview block not rendered in a column and saw that 0.6.2 might have a fix for that.

I'll now install version 0.6.2 manually but I thought you might want to know about this problem.

Cheers,
Stefan.

**Comment by ckRobinson** [comment]
Hi Stefan, strange, I am not seeing this problem on my end. I created a new vault, manually installed 0.6.0 and attempted to auto update to 0.6.2 and everything seems to have gone fine. I'll leave this issue open in case others encounter it or I discover a problem. Thanks for letting me know!

**Comment by metawops** [comment]
Now, updating from 0.6.2 (which I installed manually) to 0.6.3 worked flawlessly.
Maybe this was just a one-time hiccup. I'll close this now.
