### ISSUE TITLE
Whitespace after parameter values makes problems

### ISSUE THREAD

**Issue by metawops** [ckRobinson/multi-column-markdown#27]
Just noticed this: if there is whitespace (in my case it was a few space characters) after a parameter value the parameter's functionality doesn't work at all.
Example: I had this and was wondering why it didn't work ...
<img width="1728" alt="Screenshot 2022-07-21 at 11 58 41" src="https://user-images.githubusercontent.com/376090/180186929-b6cf68fa-b24c-4f5f-8de6-5cd500898680.png">

Turns out: there were spaces after `right` and both the two `off` values. I copy/pasted this example from some web page and apparently there were trailing spaces that were pasted. 

So, a suggestion: when reading these parameter values strip possible whitespace from them before applying. 😉

**Comment by metawops** [comment]
In the screenshot another tiny problem can be seen in the preview (rendered markdown) pane: only the second headline still has the little hide/reveal triangle in front of it. The first headline doesn't have this. Why? How should it be, consistently? With or without these little black triangles? Can I influence it?
Well, maybe that's another issue of its own ...?!

**Comment by ckRobinson** [comment]
> Just noticed this: if there is whitespace (in my case it was a few space characters) after a parameter value the parameter's functionality doesn't work at all. Example: I had this and was wondering why it didn't work ... <img alt="Screenshot 2022-07-21 at 11 58 41" width="1728" src="https://user-images.githubusercontent.com/376090/180186929-b6cf68fa-b24c-4f5f-8de6-5cd500898680.png">
> 
> Turns out: there were spaces after `right` and both the two `off` values. I copy/pasted this example from some web page and apparently there were trailing spaces that were pasted.
> 
> So, a suggestion: when reading these parameter values strip possible whitespace from them before applying. 😉

Yup, not sure how that one has slipped by this long but its an easy fix to trim off the extra whitespace when parsing the settings.

> In the screenshot another tiny problem can be seen in the preview (rendered markdown) pane: only the second headline still has the little hide/reveal triangle in front of it. The first headline doesn't have this. Why? How should it be, consistently? With or without these little black triangles? Can I influence it? And, btw, clicking the one triangle here doesn't work; it does _not_ hide the chapter below this headline (in the preview pane). Well, maybe that's another issue of its own ...?!

Just looked into this and it looks like this is Obsidian theme specific as to when the "heading collapse arrows" are being added. And actually the arrow for the other heading is there in memory but is hidden behind the column. I should be able to make sure the arrows are always hidden though, because currently collapsing headings within the columns is not supported. Should be a quick fix.

**Comment by ckRobinson** [comment]
Both of these issues should now be solved in 0.7.0 :)
