### ISSUE TITLE
Feature suggestion: space between columns

### ISSUE THREAD

**Issue by metawops** [ckRobinson/multi-column-markdown#28]
Maybe it's already there but I couldn't find that option/setting: it would be really nice & helpful if we could have a setting where we can define a space (distance) value for between the columns. Maybe in pixels or percentage of the current page width. Or maybe in any of CSS's measurements (like `em`, for example)?

**Comment by ckRobinson** [comment]
Sounds good. I have been planning a full re-work of the column layouts to allow a user to set up how many columns they want and the sizes of each so I might wait to add it in with that when it comes in. But since that might take a while I'll see what I can do to add it in sooner.

**Comment by ckRobinson** [comment]
This has now been implemented in 0.7.0. You can use the new "Column Spacing" settings flag to define the spacing in standard CSS, pt, px, %, em etc.
