### ISSUE TITLE
Sometimes directives don't get interpreted correctly

### ISSUE THREAD

**Issue by metawops** [ckRobinson/multi-column-markdown#29]
Here's a screenshot of a problem:
<img width="974" alt="Screenshot 2022-07-22 at 12 52 29" src="https://user-images.githubusercontent.com/376090/180425087-fbc9823c-343d-4221-98e2-285566cf7b61.png">

And, yes, at the end of this note there is a `=== end-multi-column` directive.

In this case I started from a "working" (minus the not correctly rendered `dataview`and `dataviewjs` blocks) two column layout and cut out the starting block
````
=== start-multi-column: homepagelayout
```column-settings  
number of columns: 2
largest column: right
border: off
shadow: off
```
````

for testing purposes. So the `=== end-column ===` and the `=== end-multi-column` directives were still in the file.

When I then pasted the cut out starting part back in the shown problem occured. 

It "feels" like after pasting the starting block back in the plugin wasn't triggered at all so that the `=== end-column ===` was just interpreted by Obsidian's markdown processor and shown as highlighted text (because two equal signs denote a highlight).

**Comment by ckRobinson** [comment]
> It "feels" like after pasting the starting block back in the plugin wasn't triggered at all so that the `=== end-column ===` was just interpreted by Obsidian's markdown processor and shown as highlighted text (because two equal signs denote a highlight).

Yea, that's exactly what happened. Essentially, each item below a start tag looks for it's "parent" above it in the document when it is first loaded by obsidian. If the parent doesn't exist it defaults back obsidian handling the rendering. So by removing the start tag you "free" all the items, then adding it back it, the "children" already looked for their parent and didn't find one so they don't know to look again.

I have some ideas on how to improve this but I think it is a relatively low priority issue right now.

**Comment by ckRobinson** [comment]
I have added a new flag type for column breaks using --- end-column --- (and all other types in the readme) which wont have the highlighting issue when this occurs. Will begin depreciating the old === column-break syntax so this will no longer be an issue.
