### ISSUE TITLE
column shows blank even though there are text inside...

### ISSUE THREAD

**Issue by erich5168** [ckRobinson/multi-column-markdown#30]
Obsidian: Version 0.15.8 (installer 0.15.6)
Multi-Column Markdown : 0.6.3

This is what I have on my `.md`.  According to the doc this should display with no problem

```
=== multi-column-start: ID_jhls
''' <-  I had to replace this with single quote or else this block code won't render correct on this post
column-settings
Number of Columns: 2
Largest Column: standard
'''
Plan text1
=== end-column ===
Plant text 2
=== multi-column-end
```

But this is what I got
<img width="684" alt="Screen Shot 2022-07-25 at 12 48 28 AM" src="https://user-images.githubusercontent.com/31515782/180657667-1f1638be-2716-4516-b6c2-7a0ba736c8b5.png">

The work around I found is you have to add some kind of header for it to show up like this

```
=== multi-column-start: ID_jhls
'''column-settings
Number of Columns: 2
Largest Column: standard
'''
Plan text1
=== end-column ===
### Plant text 2
=== multi-column-end

```

Then the column shows up but the 1st column still comes up empty
<img width="696" alt="Screen Shot 2022-07-25 at 12 49 58 AM" src="https://user-images.githubusercontent.com/31515782/180657773-5517e667-0795-493d-928f-9404c256472a.png">

Is there a setting I am missing?  Thank you

### **EDIT:**
Bullets is not supported as well?

```
=== multi-column-start: ID_dams
'''column-settings
Number of Columns: 2
Largest Column: standard
'''
Lithium batteries 3000 amp

-   1~1.5 fully charge
-   60W charing would fry the battery
-   600 Charge cycles
-   Heat issue
=== end-column ===
Real Graphene Batteries

-   20min full charge
-   Safe to use 60W charger
-   1500 Charge cycles
-   Runes much cooler and generates much less heat.
=== multi-column-end

```
I get this
<img width="735" alt="Screen Shot 2022-07-25 at 1 38 05 AM" src="https://user-images.githubusercontent.com/31515782/180659283-a1198abe-2729-4837-83a2-946c9d96b2f4.png">

When I try the work around adding header to both titles like this

```
=== multi-column-start: ID_dams
'''
column-settings
Number of Columns: 2
Largest Column: standard
'''
###### Lithium batteries 3000 amp

-   1~1.5 fully charge
-   60W charing would fry the battery
-   600 Charge cycles
-   Heat issue
=== end-column ===
###### Real Graphene Batteries

-   20min full charge
-   Safe to use 60W charger
-   1500 Charge cycles
-   Runes much cooler and generates much less heat.
=== multi-column-end

```

I get this 
<img width="727" alt="Screen Shot 2022-07-25 at 1 39 37 AM" src="https://user-images.githubusercontent.com/31515782/180659344-843fbc56-9a0e-4c4e-9567-a28c33bf1590.png">

**Comment by ckRobinson** [comment]
Hi there, your syntax is incorrect. There must be a new line before and after all of the tags (IE: column break, end tag, and after either the start OR the settings region if it exists). Try this:

> === multi-column-start: ID_jhls
> \`\`\`column-settings
> Number of Columns: 2
> Largest Column: standard
> \`\`\`
>
> Plan text1
> 
> === end-column ===
>
> Plant text 2
> 
> === multi-column-end


Or 


> === multi-column-start: ID_dams
> \`\`\`column-settings
> Number of Columns: 2
> Largest Column: standard
> \`\`\`
> 
> \###### Lithium batteries 3000 amp
> 
> -   1~1.5 fully charge
> -   60W charing would fry the battery
> -   600 Charge cycles
> -   Heat issue
> 
> === end-column ===
> 
> \###### Real Graphene Batteries
> 
> -   20min full charge
> -   Safe to use 60W charger
> -   1500 Charge cycles
> -   Runes much cooler and generates much less heat.
> 
> === multi-column-end


Obsidian passes all data to the columns as, effectively, paragraphs, headings and other content. So for simplicity of handling the data, the columns search specifically for each tag as its own "paragraph item." This is why making the surrounding text a heading kind of worked as it split the tag into a valid paragraph item with a heading item after it.

**Comment by ckRobinson** [comment]
Assuming this issue has been solved and closing.
