### ISSUE TITLE
Issue with column position

### ISSUE THREAD

**Issue by freitagfelipe** [ckRobinson/multi-column-markdown#31]
First of all I have to say that I really liked your plugin must of all because of the easy-to-use syntax, you did a great job! Now about the problem, when I try to use a single column styled with "column position: left" I got this.

![image](https://user-images.githubusercontent.com/67210292/182785895-6b715290-e7df-48b5-b8fa-d1a093f5eaeb.png)

**Comment by ckRobinson** [comment]
Hi there, this should now be fixed in 0.7.0. If you still see the problem feel free to reopen the issue and let me know.
