### ISSUE TITLE
Using horizontal rules breaks columns but fixes dataview.

### ISSUE THREAD

**Issue by AverageTrailerTrash** [ckRobinson/multi-column-markdown#33]
Since updating. I can no longer use horizontal rules in columns that have dataview elements without the layout breaking, regardless of which method is used to create them (three dashes vs three asterisks vs many underscores).

![img_withHR](https://user-images.githubusercontent.com/13239938/185553686-36253b8f-77c3-4bec-a566-dfe71a7a97af.jpg)

When they're removed, the content is positioned correctly, but some lines of dataview (value:: key) pairs are missing from the second column. (In this example, they are under the "Features" heading.)

![img_withoutHR](https://user-images.githubusercontent.com/13239938/185553690-1bf387b1-8883-45a4-9483-af367acb9b33.jpg)

Refreshing in various ways does not fix either issue. Nor does restarting Obsidian etc.

Disabling the dataview plugin fixes the column and horizontal rule issues, while disabling the multi-column markdown plugin fixes the dataview display issues.

With dataview disabled, with and without horizontal rules:
![img_withHR_DataviewDisabled](https://user-images.githubusercontent.com/13239938/185555220-adfd00a2-3c37-4c2f-9425-1d96ebc2e128.jpg)
![img_withoutHR_DataviewDisabled](https://user-images.githubusercontent.com/13239938/185555222-d5618a56-c6ff-44ae-bc47-9ca80eeb0e62.jpg)
![img_DataviewDisabled](https://user-images.githubusercontent.com/13239938/185555217-c849788e-a21b-46f1-ae08-3f78b7d69d17.jpg)

**Comment by ckRobinson** [comment]
Hi there, that is very strange. Can you provide me with the markdown you are using so I can narrow down where the bug might be?

**Comment by AverageTrailerTrash** [comment]
[Here is the markdown for a simpler demo](https://pastebin.com/aqyMbDcd).

I did some experiments and found out this:

* The (key:: value) pairs are broken in columns regardless of everything else. They only seem to work sometimes until you refresh the page. Standard key:: value ones work, so I'm guessing something about how dataview is hiding the key in the parentheses version isn't playing nicely.
* The horizontal rules won't break the layout unless a dataview block or inline query (like `=this.mykey1`) is present. And depending on which column the query/ies and horizontal rule(s) are in, it breaks in slightly different ways.

I'm using the latest version of Obsidian and both plugins, at least as of when the OP was posted.

**Comment by ckRobinson** [comment]
Sorry it took so long, but this should now be fixed as of 0.7.3
