### ISSUE TITLE
Custom content alignment in columns

### ISSUE THREAD

**Issue by lucabello** [ckRobinson/multi-column-markdown#37]
Hi!
First of all, thanks for the great plugin, I use it a lot :)

I'd love to be able to specify a setting like "alignment: center" in the multi-column settings, supporting left, center and right alignment.

I actually already implemented the feature following your style of code (specifically following the approach you have used for Content Overflow) and I would love to submit a PR to contribute to the project if you are on board with it! 
If you'd like so, I could open a PR to show you the changes and we can discuss from there.

Please let me know what you think about it!

**Comment by ckRobinson** [comment]
Hey, sorry for the long response but sounds great! Open a PR and I can take a look. I'm pretty busy right now but I'll try to get to it as soon as I can.

**Comment by ckRobinson** [comment]
This has been merged into the master branch and released in 0.7.4. Thanks for contributing to the plugin!
