### ISSUE TITLE
Embedded images are not displayed on edit mode

### ISSUE THREAD

**Issue by rotem443** [ckRobinson/multi-column-markdown#39]
**Obsidian version:** 0.15.9
**Obsidian settings:** New vault, no other plugins installed rather than `multi-column-markdown`

**Description of the issue:** While I'm on edit mode, the embedded image is not displayed, only in read mode.
**Images:**
![image](https://user-images.githubusercontent.com/16406167/192039787-ed96d9f3-5c0c-4ac5-8cbe-a4f06ed6e959.png)
![image](https://user-images.githubusercontent.com/16406167/192039855-f2a3d32c-9b64-4a3d-b897-4fff9ea1eb89.png)

**Source code:** [Try.md](https://github.com/ckRobinson/multi-column-markdown/files/9636566/Try.md)
**Source code as an image:**

![image](https://user-images.githubusercontent.com/16406167/192040645-ef177a5d-62d6-4006-ae64-3b718f14c709.png)

**Comment by ckRobinson** [comment]
Hi there, this issue should now be fixed in 0.7.3. Will close the issue but if it persists on your end let me know and I will re-open.

**Comment by rotem443** [comment]
Thanks for the quick response, it is working great, unless you specify the size on the image, in the example I provided above, you can tell that the I set the image size to "300", when I remove the `| 300` its working
