### ISSUE TITLE
Tasks Not Display in Editing Mode

### ISSUE THREAD

**Issue by kennygokh** [ckRobinson/multi-column-markdown#40]
Hi, I am using the following code within multi-column. In editing mode, the list of tasks did not display. Is it normal?

>[!multi-column]
>>[!todo|wide-2 min-0]+ 
>>
>>```tasks
>>not done
>>happens Monday 2022-09-26
>>group by filename
>>```

**Comment by ckRobinson** [comment]
Hi, that is not the proper syntax for this plugin. That appears to be syntax for the Obsidian-Columns plugin. Sorry I can't help you with this issue.
