### ISSUE TITLE
Feature Request: option to Disable Multi-column rendering in mobile

### ISSUE THREAD

**Issue by talenelat-elin** [ckRobinson/multi-column-markdown#43]

**Comment by ckRobinson** [comment]
This feature has been implemented in an upcoming build. Am doing some more testing of other fixes in the build but hope to release it over the weekend.

**Comment by ckRobinson** [comment]
This has now been implemented as of 0.7.4.

**Comment by Michael679089** [comment]
@ckRobinson so if I read my multi-column layout in my phone, it should be just one column now?

**Comment by Michael679089** [comment]
> This has now been implemented as of 0.7.4.

The multi-column layout didn't disable in my mobile. I'm on version 0.9.1
