### ISSUE TITLE
Add overflow option for column container

### ISSUE THREAD

**Issue by MatteCrystal** [ckRobinson/multi-column-markdown#45]
Right now you have a setting to set column overflow to hidden or scroll for the columns. It would be great if you could also create this option for the parent container that holds all the columns. 

(This feature will work really well in conjunction with my other two feature requests on unlimited columns and min col width)

I'm attaching a gif to give an idea of what can be done if all three features are implemented. I achieved this by setting a min width for the column of 450px and set the parent container to overflow-x: scroll;

![Obsidian_gHCJyad4HP](https://user-images.githubusercontent.com/32424764/198125933-4a23deb6-225d-47bb-91c1-7d01462948ee.gif)

of course there is only 3 columns in this example but if these features are implemented then having nay number of columns could make sense.

#46 #47

**Comment by ckRobinson** [comment]
This feature has been added in 0.8.0, columns will automatically expand beyond the view if user has defined their layout to require more than 100% of the view. Thanks.
