### ISSUE TITLE
Set minimum col width

### ISSUE THREAD

**Issue by MatteCrystal** [ckRobinson/multi-column-markdown#46]
The option to set a minimum col width would be really nice. I'm thinking something where we could enter a px or percent value. 

min col width: 250px
min col width: 100%

The percent value would be based on the current notes width. So even a width of 100% would be valid. So if note width was 500px and you made 2 columns at 100% then you would have two columns at 500px for a total of 1000px and the second column of course in this scenario would not be visible. 

(The reason to implement this makes more sense if you also implement my other two feature requests on container overflow and unlimited columns)

#47 #45

**Comment by ckRobinson** [comment]
Hi, all 3 of your feature requests sound good to me. I'll see what I can do to get them implemented but it may take a bit to find the time.

**Comment by ckRobinson** [comment]
This feature has been added in 0.8.0, you can now use an array syntax (see readme) to define the column width for each column separately which allows for shrinking columns down or expanding the, beyond 100% of the view. Thanks.
