### ISSUE TITLE
Support for more if not unlimited columns

### ISSUE THREAD

**Issue by MatteCrystal** [ckRobinson/multi-column-markdown#47]
Right now columns are limited to only 3. If you could increase this to be unlimited that would be best, However, simply hard coding up to 10 or 20 columns would be an ok if not ideal solution. 

(Unlimited columns makes sense especially if you implement my other two feature requests on container overflow and col min-width)

#46 #45

**Comment by ckRobinson** [comment]
This feature has been added in 0.8.0, thanks.
