### ISSUE TITLE
[BUG] Text disappearing inside the columns, headers getting outside it, etc..

### ISSUE THREAD

**Issue by CyRamos** [ckRobinson/multi-column-markdown#49]
hey
I noticed several issues which include text disappearing inside the columns, headers getting outside it, etc :\
I'm using RTL and disabled theme for multi check and it seems even sometimes on editing mod it got bugged.
 
editing mode -
![image](https://user-images.githubusercontent.com/40651473/198494339-1a19d1f5-81fe-4641-b360-0fc06f53fd2e.png)

on reading mode -
![image](https://user-images.githubusercontent.com/40651473/198494370-09a9134c-7f02-48fc-af00-cb18125fb93c.png)

I'll really appreciate it if you could fix it somehow.
Hopefully - thanks for all your effort!

**Comment by dancemonkey** [comment]
I'm having the same issue with one of my notes as well. All sections display in editing mode, but one multi-column designated area disappears when in reading mode. I have other sections in the same note with similar structure and content that don't have that issue.

**Comment by lrr147** [comment]
I am also having the issue. 

Edit mode MD:
![NF edit](https://user-images.githubusercontent.com/77906040/202918368-a4f83730-0a17-49a8-b43c-77fd7ece7d63.jpg)

is rendered as:
![NF Read](https://user-images.githubusercontent.com/77906040/202918376-e77e1026-bd02-4a70-a32e-3e6d0d2ecd82.jpg)

**Comment by spiritualgeek** [comment]
> I am also having the issue. When I change from --- column-end --- to --- column-break --- the issue seems to correct.
> 
> Edit mode MD: ![NF edit](https://user-images.githubusercontent.com/77906040/202918368-a4f83730-0a17-49a8-b43c-77fd7ece7d63.jpg)
> 
> is rendered as: ![NF Read](https://user-images.githubusercontent.com/77906040/202918376-e77e1026-bd02-4a70-a32e-3e6d0d2ecd82.jpg)

This did not work for me :(

**Comment by ckRobinson** [comment]
Hi all, I have made a change in 0.8.0 that should help alleviate this issue. The core problem being that obsidian passes all of the text of a paragraph as a single block of test to MCM and when a column break tag is not separated by a new line it is effectively part of the parent paragraph or list, which causes it to not be recognized. The update attempts to check for these kinds of paragraphs and lists but may not hit all cases. 

A quick fix however is making sure column break tags are always on their own line separate on both sides by a new line.
