### ISSUE TITLE
can't get it to work at all

### ISSUE THREAD

**Issue by pcause** [ckRobinson/multi-column-markdown#5]
here is my simple page:

![image](https://user-images.githubusercontent.com/1071479/152681725-eaa02e43-c731-48e0-929b-3a7919168e61.png)

and this is what I get rendered:

![image](https://user-images.githubusercontent.com/1071479/152681637-f7d61d88-f0a5-46c2-832c-0bbb04a9f430.png)

Using the Sanctum theme.    I do have a bunch of plugins, but I turned off ones that I think modify the file and also changed theme and same result

**Comment by ckRobinson** [comment]
Hey there, it looks like your "===column-end===" tag is missing spaces between the triple equals and the words. Right now the plugin looks specifically for: "=== column-end ===" with spaces separating everything. It really shouldn't be that harsh on the syntax though so I'll push out an update that fixes that requirement as well.

**Comment by ckRobinson** [comment]
Update released, let me know if it works for you.

**Comment by pcause** [comment]
check check seems fixed.  i think the problem is that it isn't clearly visible that is space is needed before and after the ===.  I thought this was the case, but the display of the readme.md makes it hard to tell.  You might also add something to the readme to clearly stae this if you want to keep that.
