### ISSUE TITLE
Having a rendering issue with a callout from the ITS theme. 

### ISSUE THREAD

**Issue by Madmaxneo** [ckRobinson/multi-column-markdown#51]
Hello, first off I realy enjoy this plugin because it helped solve an issue with an imported bulleted list. 

My issue is with rendering a callout from the ITS theme in column, in particular the [!infobox] callout from the ITS theme. 
I can sort of get it to work but the infobox blinks in and out, completely disappearing and leaving an empty column. It will then blink back in for like a split second. I assume that's a rendering issue. 
I would post a screen shot but the only shots I can get is when the box is empty. I tried adding my code but the formatting gets messed up here in github because of the "start-multi-column" code from your columns. I will post the markdown files.
The first one is the base code in the template before the imported data is added. The second one is a note with imported data in it. 

[Spell Template - Test.md](https://github.com/ckRobinson/multi-column-markdown/files/10008754/Spell.Template.-.Test.md)
[Amplify Area.md](https://github.com/ckRobinson/multi-column-markdown/files/10008761/Amplify.Area.md)

**Comment by ckRobinson** [comment]
Hi there, it seems the problem actually lies in your shorthand dataview calls rather than ITS or the callouts. I have implemented a fix but want to do some more testing to make sure it doesn't break other dataview cross compatibility so hope to get it out next week or so.

**Comment by ckRobinson** [comment]
Sorry it took so long, things got busy over the holidays, but this should now be fixed in 0.7.7, if anything else comes up feel free to let me know.
