### ISSUE TITLE
"Change text alignment within columns"

### ISSUE THREAD

**Issue by ReeceMMI** [ckRobinson/multi-column-markdown#52]
This seems to be a new feature that was implemented in the latest version, but I can't seem to find the documentation on it? How do I go about specifying what column I would like to align the text for?

Also as a bonus note. Would it be difficult to implement the option to run css styling for the multi-columns? This would also provide a more universal set of customizability that would not require any documentation. With that said, it's just a thought, and I wouldn't want to make things more difficult than they already are.

**Comment by ckRobinson** [comment]
Sorry for the extremely late response, but I have made an update in 0.8.0 that allows for defining text alignment (and other settings) on a per column basis and all the info is available in the readme. As far as custom styling that is not currently in plans for MCM but I may have time to implement it at some point. Thanks!
