### ISSUE TITLE
Image links will not render in a column.

### ISSUE THREAD

**Issue by Madmaxneo** [ckRobinson/multi-column-markdown#53]
A link to an image within my vault will not render in a column. 
I put the following code in the first columns: 
```![[Amplify Duration.png|220]]```
It doesn't render but for a few milliseconds when first opening the note.

**Comment by sappr** [comment]
I also ran into this with excalidraw embeds.

I found that if I remove the size specification from the internal link it renders normally-- so `![[Amplify Duration.png]]` instead of `![[Amplify Duration.png|220]]`. 

I would like to be able to specify the size, though.

**Comment by ckRobinson** [comment]
I am not seeing this issue on my end. Images display both scaled, and un-scaled, in live preview or reading mode. I also don't see an issue with having to reload obsidian? Do you mean close and open just the file? Is there anything else you're seeing that might help diagnose this issue?

<img width="1156" alt="Screenshot 2022-12-07 at 2 22 45 PM" src="https://user-images.githubusercontent.com/70980846/206309983-9cdec98e-415f-4002-908f-1ce6e78c3ec0.png">

**Comment by JonasSchatz** [comment]
I have the same issue and can reproduce it reliably. 

I have two-columns, with text on the left side and an image on the right side. Unscaled PNG with `![[]]` notation. The image is there when I reopen the page. When I scroll down to the bottom of the page and go back up again, it has usually disappeared. However, then it re-appears after 10 seconds or so. 

https://user-images.githubusercontent.com/13544864/219891015-cce2dbad-a641-43c6-a95d-56ae145ce752.mov

**Comment by JonasSchatz** [comment]
My workaround for now: View the page in non-source editing mode, as it seems to work there.

**Comment by ckRobinson** [comment]
I pushed a fix last week, 0.8.1, that seems to have fixed this issue, hopefully for good. Am closing this bug, if it crops up again feel free to let me know.
