### ISSUE TITLE
[BUG] The tasks are wrong.

### ISSUE THREAD

**Issue by Immortal-Sty** [ckRobinson/multi-column-markdown#54]
# What happened

It looks like something was wrong.

![](https://s3.uuu.ovh/imgs/2022/11/26/5fe820b6a93fa989.png)

And we can't finish the task by clicking.

# My obsidian

- Version: 1.0.3;
- Theme: Minimal Theme.

# Other

It's normal when the version of obsidian is 0.15.9.

**Comment by ckRobinson** [comment]
I have a fix for this coming in an upcoming build, should be out next week or so, after some more testing is done.

**Comment by ckRobinson** [comment]
Sorry it took so much longer, but this should now be fixed in 0.7.7
