### ISSUE TITLE
export pdf did not see content in column

### ISSUE THREAD

**Issue by chumido98** [ckRobinson/multi-column-markdown#57]
**in obsidian:**
![CleanShot 2022-12-07 at 21 45 12@2x](https://user-images.githubusercontent.com/61721378/206209610-7b34d8e3-c483-4860-bcdf-80e2b33c7112.jpg)
**exported:**
![CleanShot 2022-12-07 at 21 45 29@2x](https://user-images.githubusercontent.com/61721378/206209643-a79d4157-4236-4dd6-b89b-e8d0cc0b5354.jpg)

please check, thank you

**Comment by chumido98** [comment]
https://github.com/ckRobinson/multi-column-markdown/issues/10#issuecomment-1279394800

**Comment by ckRobinson** [comment]
I have implemented a fix for this in an upcoming build I'll release soon. In the mean time export to PDF is not actually broken, as far as my tests show, it just doesn't display the proper error message when attempting to export from Live Preview. If you swap to reading mode and export everything renders properly.

**Comment by ckRobinson** [comment]
This has now been fixed in 0.7.7, you still must use reading mode to export to PDF but attempting to export from live preview now properly displays an error message.
