### ISSUE TITLE
Double checkboxes

### ISSUE THREAD

**Issue by The-Eighth-Man** [ckRobinson/multi-column-markdown#58]
As the title suggest I'm seeing double checkboxes when implementing them. I show a single column as an example.

![image](https://user-images.githubusercontent.com/20918019/207094418-5ce1242d-dfa2-4602-a18d-f42612a6ddda.png)

Their margin is a feature of my setup, otherwise they would be overlaped and would't be possible to click it because the second checkbox can't be selected. My code is fairly simple.

![image](https://user-images.githubusercontent.com/20918019/207094380-bf1f8131-080b-4559-8fea-aedee1729369.png)

I believe the cause of this has to be that when creating a checkbox it doubles it as shown here.

![Screen Shot 2022-12-12 at 10 49 14 AM](https://user-images.githubusercontent.com/20918019/207092273-e4812b5d-0e19-4a4f-85a8-24096cc1e95e.png)

This behavior only happens inside multi-cols. Oddly, it doesn't happen with normal lists (- item 1 / - item 2).

I have Obsidian version 1.1.3 and multi-cols version 0.76.

**Comment by ckRobinson** [comment]
This should now been fixed in 0.7.7, if the problem remains, feel free to let me know.

**Comment by The-Eighth-Man** [comment]
Hi, it seems the problem was fix but partially.

If I have two following tasks, they are fine.
![image](https://user-images.githubusercontent.com/20918019/223750950-1811f808-3f18-4d42-ae69-abc7f87a8af4.png)

But when one is nested the parent becomes double again.
![image](https://user-images.githubusercontent.com/20918019/223751283-33795640-a337-488f-99b3-90ce91de3039.png)

**Comment by The-Eighth-Man** [comment]
I added the following lines in a snippet to allign the checkboxes.
```.block-language-start-multi-column.mcm-column-root-container ul li .task-list-item-checkbox {
    margin-left: -20px;
}

.block-language-start-multi-column.mcm-column-root-container ul.contains-task-list{
    margin-left: -3px;
}
```
<img width="154" alt="image" src="https://user-images.githubusercontent.com/20918019/223773135-e93ba61f-8a31-4dc9-9852-e8f998d91395.png">
But I cannot check the parent box, only the child. To check it I have to do it on source mode.
