### ISSUE TITLE
[Feature requeset] Add option to turn Live Preview off

### ISSUE THREAD

**Issue by sunrisewestern** [ckRobinson/multi-column-markdown#59]
Live Preview of multi-column causes some unexpective issue, but I don't want to turn Live Preview off for the whole file. It would be better to add option to turn Live Preview off.

**Comment by ckRobinson** [comment]
Sorry for the extremely long response time but no sorry, I believe adding another command or way to disable just MCM will be too confusing and lead to other issues. Thanks.
