### ISSUE TITLE
Images may not be displayed in columns.

### ISSUE THREAD

**Issue by mtg20** [ckRobinson/multi-column-markdown#60]
Hi, thank you for creating this plugin!I have a small problem to report.

Obsidian: v1.0.3
multi-column : 0.7.6
No plug-ins are installed.

Images may not be displayed; they are displayed when written in the first column, but not when written in the second column.
I'm not familiar with the program so sorry if I'm missing something, but I'd like to display the image in the second column the way it's written.

```start-multi-column  
ID: ExampleRegion3  
```
```
Column 1

![[img-20221223-2.png]]

=== end-column ===

Column 2

![](img-20221223-2.png)

=== end-multi-column
```

Images:
![](https://user-images.githubusercontent.com/121297787/209343742-a26e80d0-efa0-42b3-8db4-a79c000b967f.jpg)
![](https://user-images.githubusercontent.com/121297787/209344241-2e99344e-309b-44fa-98c4-1c9340e892ca.jpg)

Thanks so much!

**Comment by mtg20** [comment]
It showed up when I switched to leading view! It would be great if it could be shown in real-time preview if possible.

**Comment by ckRobinson** [comment]
I have implemented a fix for this issue that will be in the next update, which I hope to release soon.

**Comment by mtg20** [comment]
Thank you for fixing the problem. You have made a good plugin and I appreciate it.
