### ISSUE TITLE
Screenview scrolls downward when clicking

### ISSUE THREAD

**Issue by A000045** [ckRobinson/multi-column-markdown#61]
Whenever I tried to use this plugin, I've had this strange issue : after I set my columns, whenever I click somewhere on the screen it will "jump" (scroll) downward, so that the document becomes unusable... Therefore I stopped using the plugin..

**Comment by ckRobinson** [comment]
I have not encountered a problem like you describe in my personal use or test cases. Will have to investigate more to see what I can find.

**Comment by surajwy** [comment]
Even I face this issue on every single note in which I have used this plugin.
I also have 1 observation. If I use this plugin to create columns in the mid part of a the note file, then If I click on any text above this column plugin, jumping does not happen. If I click on any text below this plugin's column, jumping happens.

---
Obsidian version - Version 1.1.9 (Installer 1.1.9)
Multi-column markdown plugin version - 0.7.7
Mac - Apple M1 Pro
OS - Mac OS Montery (version 12.5.1)

**Comment by ckRobinson** [comment]
I have implemented a fix for this in 0.8.0, see #69 for more info.
