### ISSUE TITLE
Embedding PDF in column

### ISSUE THREAD

**Issue by alexalvaradorojas** [ckRobinson/multi-column-markdown#64]
Hello! Awesome work on the plugin; it is great for notetaking and organization. I'm wondering whether embedding PDFs directly on a column is supported. I imagine a table of two columns where one column displays text in bullet points and the other column displays the PDF for reference.

I appreciate any thoughts on this!

**Comment by ckRobinson** [comment]
Hi, I have made a change in 0.8.0 that should fix embedding PDFs within columns. Thanks.
