### ISSUE TITLE
Multiple bug issues (not folding, jumping to the bottom, bullet points not appearing, embedded images not appearing in reader view)

### ISSUE THREAD

**Issue by danuhorus** [ckRobinson/multi-column-markdown#67]
Hi there, I've been having some issues with bugs concerning this plugin. First, when I have a column open anywhere on a note, clicking anywhere _underneath_ that column will result in the editor view going all the way to the bottom. It doesn't seem to trigger when clicking above it. Folding it seems to remove the issue.

The second issue is that bullet points aren't appearing in the 2nd and 3rd column. For example, in the first column on the left, I'll have a list of bullet point notes, and those will appear just fine. But if I try to make another list in the 2nd and 3rd columns, those simply won't appear. The heading will show up just fine, however. To get around this, at the very end of the column, I usually put in a header to serve as space filler such as # - - -, which then causes anything between it to finally appear.

Another issue that columns won't fold into anything smaller than Heading 1. H2 and beyond, when I try to fold it, there's some kind of visual glitch where the columns remain outside the header, but with the text MUCH bigger. It all looks like headings. Unfolding it fixes the formatting.

And finally, an image that I'm able to put inside the column in editor mode won't show up in preview mode.

**Comment by ckRobinson** [comment]
Hi there,

> First, when I have a column open anywhere on a note, clicking anywhere _underneath_ that column will result in the editor view going all the way to the bottom. It doesn't seem to trigger when clicking above it. Folding it seems to remove the issue.

This issue has been attempted to be fixed in 0.8.0.

> The second issue is that bullet points aren't appearing in the 2nd and 3rd column. For example, in the first column on the left, I'll have a list of bullet point notes, and those will appear just fine. But if I try to make another list in the 2nd and 3rd columns, those simply won't appear. The heading will show up just fine, however. To get around this, at the very end of the column, I usually put in a header to serve as space filler such as # - - -, which then causes anything between it to finally appear.

I am not seeing this issue but it may be due to my test cases, can you supply me with some raw markdown that is displaying this issue?

> Another issue that columns won't fold into anything smaller than Heading 1. H2 and beyond, when I try to fold it, there's some kind of visual glitch where the columns remain outside the header, but with the text MUCH bigger. It all looks like headings. Unfolding it fixes the formatting.

MCM was not intended on being folded into headings, I can look into the issue but I am unsure if it is solvable at this point.

> And finally, an image that I'm able to put inside the column in editor mode won't show up in preview mode.

I have made some changes that should fix this issue, but I have another update in the works that should put it to bed that should be released soon.
