### ISSUE TITLE
Extremely Bad Bug - Page Jumping when Selecting Text Lines

### ISSUE THREAD

**Issue by greenbluewatercourse** [ckRobinson/multi-column-markdown#69]
**Quick Version**: this bug causes text clicked below a Multi-Column region to "Jump" or "Shift" the entire screen downward until the user is staring at the bottom of their page. They cannot navigate to edit text because every time they Click on a section below the Multi-Column region, the screen jumps.

**Severity**: extreme; this bug makes the plugin extremely user-unfriendly.

**To Reproduce**:

1. insert a Multi-Column.
2. insert some regular text **inside of** the Multi-Column region.
3. insert some regular text **below (outside-of)** the Multi-Column region.
4. make sure you stay in **Editing Mode**.
5. now, simply Click your mouse anywhere in the regular text that is located **below (outside-of)** the Multi-Column region. You should notice your screen "Jumps" down. Click as much as you want, and you will continually have your screen "Shifted downward" toward the bottom of the document.

**Why is this a problem**: If it's not obvious, this is a **MAJOR** usability issue. If the user wants to click on a section of text to modify it, they will find their screen **jumping all over the place**. If they try scrolling up to find the spot they want to edit again, they will try Clicking it and, again, their screen will be thrown downward and they will lose track of where they were.

**Workaround**: The **ONLY** workaround I have found for this problem is to use the Arrow Keys to help navigate without the screen jumping around as much. Note: this does **NOT** fix the issue, and it is extremely frustrating to have to "Arrow" your way to the text you want to edit because you literally can't Click on it without the plugin throwing you to the bottom of the screen.

**Cause of the Problem**: I'm not 100% positive, but I would guess that what is happening is that the Obsidian is trying to "jump" to the correct line the user is looking at, however (because of the Multi-Column Plugin), text that is normally located in one spot is actually located somewhere else. In other words: the text is not **actually** where it appears to be, so when the user clicks on it, Obsidian attempts to "jump" to the location it thinks the text is. This is just my guess, but either way: this is such a serious usability issue that I have had to Uninstall the plugin.

**Comment by The-Leveret** [comment]
I'm experiencing the same issue. It's incredibly frustrating to write anything on a page with columns. If I disable the plug-in, I can write on the page without it jumping around, but that's a hassle.

**Comment by adrienthebo** [comment]
Similarly to @The-Leveret  I'm experiencing the same issue on a 2021 MBP M1; the jumping gets worse as I use multiple multi-column sections within a single note.

**Comment by enriquedecote** [comment]
agree, pretty bad, same exact config as adrienthebo

**Comment by rienzian** [comment]
I am experiencing this as well and its making this plugin very difficult to use. I use the plugin to write video scripts with what is to be read in 1 column, and what is it be shown, in the other column. This bug makes it very challenging to navigate between sections of text as it jumps right to the end when use the down arrow to navigate to another multi-column section. Presently, there is no workaround. Using the arrow keys makes things a little easier but does not solve the problem.

**Comment by ckRobinson** [comment]
Hi all, I have attempted to alleviate this bug in the latest release 0.8.0. The core problem of this bug comes down to how Obsidian handles the click interaction and it conflicting with installed CM6 plugins. For the time being the fix re-adjusts the viewport to be centered on the cursor after any viewport adjustments have been made by Obsidian. If I discover a better fix for this problem in the future it will be implemented, but for now I will be closing this issue.
