### ISSUE TITLE
clarify the ID

### ISSUE THREAD

**Issue by pcause** [ckRobinson/multi-column-markdown#7]
the ID is new.  is this *ONLY* needed if there are multiple uses of multi-columns in the document?   Can I use the same ID in multiple documents as long as no document has 2 or more multi-column regions?  Perhaps the doc should read:

After defining the start tag you must declare an ID for the region. The ID is used to differentiate between different regions if there are multiple in the same document. Each ID must be unique or unexpected render issues may occur.  An ID may be used across multiple documents so that, for example, you can use the ID "dailynote" in the template used for your Periodic Notes.

**Comment by ckRobinson** [comment]
Right now the ID is still required even when only a single region is in a document. But you are correct, they only need to be unique within a single document. I have updated the README based on your recommendation.
