### ISSUE TITLE
Multiple colums in Editor / View mode only?

### ISSUE THREAD

**Issue by feedhopper** [ckRobinson/multi-column-markdown#70]
Hi,

this is GREAT.

However, it requires to set up texts using the multi-column-modifier.
It is something I rarely want to do. Why?

1. It introduces additional data that is not needed from the content side of things
2. it breaks compatibility with other Markdown viewers
3. I need to actually do it

What I would ABSOLUTELY LOVE to have in addition to the existing capabilities:

A "hack" of the current view modes in both editor and viewer that allows me to set a multicolumn style reflow of my text. This would SO MUCH ease my work. Why?

I use a 42 inch monitor and would love to make use of its full width. The way it is, however, makes me scroll 2-3 times as much. This is especially annoying when I have to read long texts as I love excercise a little while doing so. Having to scroll every 10-15 seconds makes this virtually impossible.

So: Is there any way to implement something like the multi-column view in Calibre viewer? There, you can define separate scenarios and the amount of colums to be displayed. The scrolling behaviour is then not continuous but page by page with the text being dynamically reflowed according to the setting.

In any case: THANKS a LOT for both the plugin AND your patience to read through all of this.

BEST!!!!

**Comment by ckRobinson** [comment]
Hi, I have added a new feature in 0.8.0 that allows you to set an entire document to reflow into a multi-column state using Obsidian's frontmatter document metadata. You can find the syntax in the README. There are some limitations to how it is implemented but it should hopefully work how you want it.
