### ISSUE TITLE
[FR] Pandoc Compatible Syntax? (fenced-divs)

### ISSUE THREAD

**Issue by Servinjesus1** [ckRobinson/multi-column-markdown#71]
Multicolumn Markdown is available in Pandoc via a [columns](https://github.com/dialoa/columns) filter. While this isn't native pandoc, the filter seems prolific and compatible enough to be considered part of the pandoc ecosystem, and the default go-to for pandoc multicolumns. It follows the [`fenced_div`](https://pandoc.org/MANUAL.html#divs-and-spans) syntax of native Pandoc, which makes sense as the multi-column environment is a type of div.

I would love to see this plugin adopt this syntax so that my markdown documents are compatible with pandoc. Right now, I'm not sure where current syntax draws its inspiration from, and if it's unique to this plugin, that would contribute to [vendor lock-in](https://en.wikipedia.org/wiki/Vendor_lock-in) in my notes, which I would like to avoid if possible.

**Comment by ckRobinson** [comment]
Hi there, pandoc's fenced divs syntax support has now been added in 0.8.0. Not all of the syntax is available due to some limitations but the core functionality is there and should allow you to use columns in both programs.
