### ISSUE TITLE
Transclusions of rendered Buttons behave erratically & buttons do not execute actions.

### ISSUE THREAD

**Issue by inakarmacoma** [ckRobinson/multi-column-markdown#72]
Repro steps:
- Install buttons plug-in
- Create 3 buttons
- Create a button transclusion for each

`![[Buttons#^home-css-snippets-button]]` 
`![[Buttons#^home-bookmark-button]]`

Place those buttons in multi-column:

`

```start-multi-column  
ID: ExampleRegion5  
number of columns: 3  
largest column: Standard  
```

## Column 1

![[Buttons#^home-css-snippets-button]]

--- end-column ---

## Column 2

![[Buttons#^home-bookmark-button]]

--- end-column ---

## Column 3

![[Buttons#^home-bookmark-button]]

=== end-multi-column
`

Expected behavior: 
1) Renders 3 buttons always
2) Buttons, when clicked, workl.

Observed behavior
1) Buttons render erratically, at random, and with small edits ot text in any column can cause the button to jump from one column to another or even disappear entirely.
2) Buttons, even when rendering correctly, do not perform any action when clicked.

---

Very cool idea, but can't use it presently :(

**Comment by ckRobinson** [comment]
Hi there, I have implemented a fix that should fix the intractability problem in Reading mode only. Intractable buttons are not currently supported within columns in Live Preview mode. 

The layout issue may be a separate issue but I did not experience it in my testing. If it is still occurring on your end feel free to let me know.
