### ISSUE TITLE
.webp images don't render on Live Preview

### ISSUE THREAD

**Issue by otherfutures** [ckRobinson/multi-column-markdown#76]
.webp images consistently don't render on Live Preview despite showing up on Reading mode; the image shows up only as the file name in plain text within the multi column. 

More specifically & strangely, the images consistently render on plain text Live Preview (i.e. when ```multi-column-settings``` & other source text is visible), but not when the Reading mode preview is generated (i.e. when the multi columns are visible).

**Comment by ckRobinson** [comment]
Hi there, I have made a fix for .webp images rendering in live preview. It will be coming out with the next patch, thanks.
