### ISSUE TITLE
Extra spaces added in Live Preview

### ISSUE THREAD

**Issue by otherfutures** [ckRobinson/multi-column-markdown#77]
Columns render with extra spaces between lines when headings & bullet points are used. Spacing is correct within the bullet points themselves (i.e. long bullet point text wraps/continues to the next line without inserting extra spaces between lines, but there are extra spaces in between bullet points as the in the below).

Example:

### Heading
<br>
- This is a bullet point
<br>
<br>
- This another bullet point

**Comment by ckRobinson** [comment]
Hi, I can't seem to see what you are describing on my end, can you provide a screenshot and the raw markdown, column syntax and all that causes the issue?

**Comment by otherfutures** [comment]
Sorry for the delay: I don't have a screenshot at the moment, but this is the raw markdown below (with some escape character backslashes [i.e. \```] before the column syntax so that everything's grouped together). 

It renders without the extra spaces in Reading mode, but it also requires `<br>` to space out vs. Live Preview which has spaces that're too wide (especially for bullet points). I can get the look to be ok using HTML, but I'd rather use Markdown if possible:

```
\```start-multi-column
ID: ID_gr9j
Number of Columns: 2
Largest Column: right
border: on
shadow: off
\```
## <%* tR += `${title}` %>

![[Template Placeholder.jpg]]

### Bio. Info.
- \#birthday 
- Nationality:
- Hometown:

- Occup.:

- Rel.:<br>
	- N/A
<br><br>
### Social Info.
- House:
- Connections:

### Other Notes
-
```

**Comment by ckRobinson** [comment]
Ah, I see what you mean, yea that is weird. In live preview I hand off the raw markdown to Obsidian to render before then splitting it into columns, so there's probably something wrong in that area of the code. I'll have to investigate to figure out more.

**Comment by ckRobinson** [comment]
Hi there, sorry for the super long response time but if you're still using the plugin I have made a change in version 0.9.0 that should fix this issue, closing the issue but feel free to let me know if it is still occurring, thanks.
