### ISSUE TITLE
Dataview query not visible in editing mode

### ISSUE THREAD

**Issue by TimothyMRead** [ckRobinson/multi-column-markdown#78]
I have a data view query in the second of two columns:
````
```start-multi-column  
number of columns: 2  
```

Blah blah blah

--- end-column ---

**Daily and Monthly Notes:**
```dataview
List From "Daily Notes"
WHERE file.day = date(today) OR
contains(file.tags, "MonthlyNote")
sort file.name asc
``` 

--- end-multi-column
````

Which works perfectly in edit mode, **while** I am actually editing the above column definitions, but when I click out of the code, for example, to the paragraph above,  but still with the page in edit mode, the second column just outputs:

Daily and Monthly Notes

 “Loading…”

and the dataview query never loads. If I then change to reading mode for the page, it loads perfectly.

Any idea why and what I can do about it?

Thanks,

**Comment by ckRobinson** [comment]
Hi there, dataview and some other plugins are not cross-compatible in live preview and only work in reading mode, you can see the list of known issues here: [Cross Compatibility](https://github.com/ckRobinson/multi-column-markdown/blob/master/documentation/CrossCompatibility.md). Sorry for the inconvenience.
