### ISSUE TITLE
File Explorer Highlighting Issue

### ISSUE THREAD

**Issue by ShreyaPatibanda** [ckRobinson/multi-column-markdown#79]
when I toggle on the multi-callout snippet, when I hover over the file explorer on the left, it doesn't highlight the whole bar, it just highlights based on the title size.

https://github.com/ckRobinson/multi-column-markdown/assets/73957016/f99378af-7a07-4cf1-9d8d-57716b45c749

**Comment by ckRobinson** [comment]
That bug is not for this plugin, you are looking for this project: [https://github.com/efemkay/obsidian-modular-css-layout](https://github.com/efemkay/obsidian-modular-css-layout)

**Comment by ShreyaPatibanda** [comment]
Oops im so sorry
