### ISSUE TITLE
compatibility with tasks plugin queries

### ISSUE THREAD

**Issue by pcause** [ckRobinson/multi-column-markdown#8]
If I have 2 columns and the second column has a ```tasks query and switch to reading mode, I can get the tasks I ask for but I can't click the completed check box or get the hot key to bring up the form for a task.  this works in preview mode if the query isn't in multi-column mode

**Comment by ckRobinson** [comment]
I've identified the problem and have a potential fix for it working. However, fixing this bug is causing bugs in other areas so am still working on cleaning that up. Hopefully have something out within the next day or so.

**Comment by ckRobinson** [comment]
Just released 0.4.3 which should fix this problem. I believe I ironed out any other bugs caused by fixing this but feel free to let me know how it goes.
