### ISSUE TITLE
Buttons plugin issues after the latest update

### ISSUE THREAD

**Issue by cakechaser** [ckRobinson/multi-column-markdown#82]
After the latest update I’m experiencing issues with the Buttons plugin.
https://github.com/shabegom/buttons

I’m displaying buttons in a 2-column view, and after the update some of the buttons are just randomly not rendered.
The ones that are rendered, are not working and not performing any action when pressed.

If I disable this plugin, all the buttons are displayed.

Can provide more details if necessary.

**Comment by ckRobinson** [comment]
I have pushed a new version, 0.8.2, that should fix the problem. If you still see the problem on your end let me know and I will re-open the issue.

**Comment by cakechaser** [comment]
Thanks for the quick reply! Unfortunately after the update the issue is still there, nothing has changed.

**Comment by ckRobinson** [comment]
Sad to hear, everything seems to work on my end with my test cases, can you provide the markdown that you're seeing the issue with?

**Comment by cakechaser** [comment]
Sure! Here's the exact markdown I used for testing.
Tested in a new vault with only these 2 plugins installed, no settings changed in Obsidian or the plugins.

````

```start-multi-column  
ID: ExampleRegion2
number of columns: 2  
```

w

--- end-column ---

```button
name test
type command
action Rename file
```
^button-q1k6

=== end-multi-column

````

In preview mode the note looks like this:
<img width="761" alt="image" src="https://github.com/ckRobinson/multi-column-markdown/assets/16690476/772d3ce4-a18c-45af-9342-37335957160b">

**Comment by ckRobinson** [comment]
Alright, just released 0.8.3 that should fix it, it was a test case that I hadn't covered. Seems to be working on my end, hopefully everything works on yours.

**Comment by cakechaser** [comment]
It works perfectly for me as well, thanks for the quick resolution!

**Comment by ckRobinson** [comment]
Glad to hear!
