### ISSUE TITLE
Columns content doesnt render in live preview

### ISSUE THREAD

**Issue by Fuergrissa1** [ckRobinson/multi-column-markdown#84]
I use a lot of lists in my daily note so I have tried to organize them in columns. The lists are made with obsidian tasks plugin. here is what they look like in reading view. Apologies if this is the intended way for columns to work, but I don't really ever use reading view so it really defeats the point for me.

![image](https://github.com/ckRobinson/multi-column-markdown/assets/88895680/f0ee5f68-ce84-4b86-afde-5a0a143c9a8c)

and editing with live preview
![image](https://github.com/ckRobinson/multi-column-markdown/assets/88895680/9fb20dd0-9b18-4410-a6a4-70fff60ef1a0)

and the source:

### Research Projects

\`\`\`start-multi-column  
ID: TaskTracking 
number of columns: 2  
largest column: standard
border: off
\`\`\`

\> [!warning]+ Over Due Tasks
\> \`\`\`tasks
\> not done
\> sort by due date
\> due before 2023-06-28
\> hide due date
\> hide backlink
\> limit 5
\>\`\`\`

\> [!Warning]+ Unscheduled Tasks
\> \`\`\`tasks  
\> not done  
\> no due date
\> \`\`\`

 
--- end-column ---
\> [!todo]+ Today's Tasks
\> \`\`\`tasks
\> not done
\> due 2023-06-28
\> sort by path
\> sort by priority
\> hide due date
\> hide backlink
\> limit 5
\> \`\`\`

\> [!todo]+ Upcoming Tasks
\> \`\`\`tasks  
\> not done  
\> due after 2023-06-28  
\> sort by due date
\> sort by priority
\> \`\`\`  

--- end-multi-column

\> [!success]+ Tasks Done Today
\> \`\`\`tasks 
\> done 2023-06-28
\>  hide due date
\>  hide backlink
\> \`\`\`

**Comment by ckRobinson** [comment]
Yeah, sorry, currently a lot of plugins are not cross-compatible within LivePreview mode. I recently discovered a fix for that issue that will add a lot of the cross-compatibility back in, but it is still in the works and have not yet confirmed if Tasks will be compatible after the update.

**Comment by albertoloscerritos** [comment]
Are there any news regarding this problem?
Thanks :)

**Comment by ckRobinson** [comment]
Hi there, version 0.9.0 has been released and does increase the amount of cross compatibility in LivePreivew, but sadly the Tasks plugin seems to work differently and still does not render in LivePreview. I have added an error message rather than rendering nothing but do not have a solution. Sorry for the inconvenience.

**Comment by albertoloscerritos** [comment]
Hi, thanks for letting us know.
