### ISSUE TITLE
bug: the new version, TASKS plugin link can'not jump

### ISSUE THREAD

**Issue by gy-git** [ckRobinson/multi-column-markdown#86]
tasks plugin code:

  ``` tasks
  not done
  filename includes note
  ```

then:
![bug](https://github.com/ckRobinson/multi-column-markdown/assets/26562668/cd11d388-675e-4979-870e-98235a9d3eca)

Clicking on the link did not respond

**Comment by Leo310** [comment]
Same for me. All task features are unusable with multi-column-markdown. Can't even check the tasks

**Comment by ArcticDev78** [comment]
Same issue for me as well :/

**Comment by ckRobinson** [comment]
Hi there, version 0.9.0 has been released containing a fix for this issue, both the checkboxes and the links should properly work in reading mode. If you are still experiencing issues feel free to let me know and I'll try to take a look, thanks.

**Comment by AaronKnowls** [comment]
Great news! Thanks!
