### ISSUE TITLE
Columns not visible in reading mode

### ISSUE THREAD

**Issue by Asetnozama** [ckRobinson/multi-column-markdown#90]
For me suddenly the columns are not visible anymore in reading mode. Changing to editing mode shows them again. 
Anybody else experiencing this issue?

**Comment by Spiderbrigade** [comment]
Can confirm the same issue. Columns appear correctly only in editing mode.
Interestingly this change does not seem to have coincided with an Obsidian version update.

**Comment by Spiderbrigade** [comment]
I actually can't replicate the issue anymore. It's possible this was caused by an issue with another plugin that has since updated.
