### ISSUE TITLE
Tables in columns not aligning

### ISSUE THREAD

**Issue by TCArknight** [ckRobinson/multi-column-markdown#95]
Hello! I love your plugin, it's really helped me with formatting information for my ttrpg games. I do seem to have come across an issue. 

I'm trying to layout three tables across a page. It works great, but it doesn't seem that if you have a table within a column, that the table is aligned with the column method. 

My settings:
![image](https://github.com/ckRobinson/multi-column-markdown/assets/4914790/5f4d061f-3902-4416-86ac-457fb13396b6)

Results:
![image](https://github.com/ckRobinson/multi-column-markdown/assets/4914790/ae41680f-712c-499f-8876-01b46a7f8e47)

I would expect the middle table to be centered in the column, and the right-hand table to be to the right of the column. Is this possible or is this something inherent to the tables themselves?

**Comment by TCArknight** [comment]
Also, none of the header level entries apparently can display in the columns...

**Comment by Skulshie** [comment]
I've looked into ways to center tables and found your post which led me into looking into ways to center markdown tables and I think I've found your solution in this post: [Is it possible to center tables in a markdown file?](https://stackoverflow.com/questions/24127507/is-it-possible-to-center-tables-in-a-markdown-file)

### It's to enclose your table with: `<div align="center">` and `</div>` (sry im not too familiar with code language idk what these r called :')) ) to turn this:


| test | check 1 |  
|----|-------|  
|  1234567810   |    1234567810    |


into looking something like this:


<div align="center">

| test | check 1 |  
|----|-------|  
|  1234567810   |    1234567810    |

</div>


Raw looks something like this:


```
<div align="center">

| test | check 1 |  
|----|-------|  
|  1234567810   |    1234567810    |

</div>
```


***

**Fair warning tho**: idk y but testing in Obsidian seems to have removed  the table borders for some reason, i'm not too sure how to get it back, but using it with another column plugin called [Obsidian Columns](https://github.com/tnichols217/obsidian-columns) doesn't seem to have the same issue (tho Obsidian columns don't have column borders) so use whichever and however you see fit ig:

![image](https://github.com/ckRobinson/multi-column-markdown/assets/57561913/d3b0b910-8531-451d-9cb4-1bc06718b5b0)

**Comment by ckRobinson** [comment]
Hi there, glad you have been enjoying the plugin! 

I have added a new setting: 
```
Align Tables to Text Alignment: True/False
```
to the list of valid column region settings in 0.9.0. I have also added a switch, in the plugin settings window, to set the default behavior on whether to align tables with text.

Will be closing this ticket.
